import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, TouchableOpacity, View } from 'react-native';
import { Button, Chip, HelperText, IconButton, Menu, Switch, Text, TextInput } from 'react-native-paper';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import moment from 'moment';
import { PageContainer, PageContent, NoContent, DateTimeField, LocationPicker, LatLng } from 'skintyee/components/layout';
import { useAppDispatch, useAppSelector } from 'skintyee/store';
import { loadDirectory } from 'skintyee/store/modules/directory';
import { updateMeeting } from 'skintyee/store/modules/meetings';
import { apiFactory } from 'skintyee/store/apis';
import { MeetingLink } from 'skintyee/models';
import { theme } from 'skintyee/styles';

// Admin: edit an existing band meeting. Matches the CreateMeeting form
// field-for-field (type chip / source chip / title / location / time /
// agenda / Teams toggle / attendees) so the experience is consistent.
//
// Source is read-only — Graph can't move events between calendars in
// a single PATCH (would require delete+recreate). If you need to move
// an event to a different calendar, delete this one and reschedule.
//
// Saves go through PATCH /v1/meetings/:id which calls Graph PATCH
// against the event's calendar path (derived from sourceIndex).

interface MeetingType { slug: string; displayName: string; category: string; description: string }
interface MeetingSource { index: number; kind: 'me'|'user'|'group'; name: string; upn?: string; groupId?: string }

const TYPE_ICONS: Record<string, string> = {
  'band-meeting':    'account-group',
  'council-meeting': 'gavel',
  'staff-meeting':   'briefcase',
  'public-event':    'star',
  'closed-session':  'lock',
};

function defaultAudienceFor(typeSlug: string): (m: any) => boolean {
  switch (typeSlug) {
    case 'band-meeting':
    case 'public-event':
      return (m) => m.accountType === 'licensed-user';
    case 'council-meeting':
    case 'closed-session':
      return (m) => m.accountType === 'licensed-user' && (m.bandGroups ?? []).includes('council');
    case 'staff-meeting':
      return (m) => m.accountType === 'licensed-user' && (m.bandGroups ?? []).includes('management');
    default:
      return (m) => m.accountType === 'licensed-user';
  }
}

export default function EditMeeting({ route, navigation }: any) {
  const dispatch = useAppDispatch();
  const id = route?.params?.id;
  const meeting = useAppSelector((s) => s.meetings.entities.find((m: any) => m._id === id));

  // Form state — initialized from the existing meeting
  const [title, setTitle] = useState(meeting?.title ?? '');
  const [location, setLocation] = useState(meeting?.location ?? '');
  const [coords, setCoords] = useState<LatLng | undefined>(
    meeting?.lat != null && meeting?.lng != null ? { lat: meeting.lat, lng: meeting.lng } : undefined
  );
  const [startsAt, setStartsAt] = useState((meeting as any)?.startsAt ?? moment().toISOString());
  const [agenda, setAgenda] = useState(meeting?.agenda ?? '');
  const [typeSlug, setTypeSlug] = useState<string>((meeting as any)?.type ?? 'band-meeting');
  const sourceIndex: number | undefined = (meeting as any)?.sourceIndex;
  const [isOnlineMeeting, setIsOnlineMeeting] = useState<boolean>((meeting as any)?.isOnlineMeeting ?? false);
  // Editable "Links:" section — round-trips through Graph as plain
  // text appended to the body. Conference details (Teams join URL,
  // meeting ID, passcode) are auto-generated by Graph when
  // isOnlineMeeting=true, so they're shown read-only further down.
  const [links, setLinks] = useState<MeetingLink[]>(((meeting as any)?.links ?? []) as MeetingLink[]);
  const conference = (meeting as any)?.conference as undefined | { joinUrl?: string; meetingId?: string; passcode?: string; helpUrl?: string };

  const addLink = () => setLinks((prev) => [...prev, { label: '', url: '' }]);
  const updateLink = (i: number, patch: Partial<MeetingLink>) =>
    setLinks((prev) => prev.map((l, idx) => (idx === i ? { ...l, ...patch } : l)));
  const removeLink = (i: number) =>
    setLinks((prev) => prev.filter((_, idx) => idx !== i));

  const [catalog, setCatalog] = useState<{ types: MeetingType[]; sources: MeetingSource[] }>({ types: [], sources: [] });
  const [catalogError, setCatalogError] = useState<string | undefined>();
  const [typeMenuOpen, setTypeMenuOpen] = useState(false);
  // Anchor width captured via onLayout so the dropdown's content
  // matches the field's width instead of sizing to its widest item.
  const [typeAnchorWidth, setTypeAnchorWidth] = useState<number | undefined>();
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | undefined>();

  // Attendees prefilled from the existing event's attendees[]
  const directory = useAppSelector((s) => s.directory.entities);
  const licensedUsers = useMemo(
    () => directory.filter((m: any) => m.accountType === 'licensed-user' && m.upn),
    [directory]
  );
  const initialAttendeesKey = JSON.stringify((meeting as any)?.attendees ?? []);
  const [attendees, setAttendees] = useState<Set<string>>(
    new Set(((meeting as any)?.attendees ?? []).map((a: any) => (a.upn ?? '').toLowerCase()).filter(Boolean))
  );
  useEffect(() => {
    setAttendees(new Set(
      ((meeting as any)?.attendees ?? []).map((a: any) => (a.upn ?? '').toLowerCase()).filter(Boolean)
    ));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialAttendeesKey]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const r = await (apiFactory() as any).meetings.types();
        if (!cancelled) setCatalog(r);
      } catch (e: any) {
        if (!cancelled) setCatalogError(e?.message ?? String(e));
      }
    })();
    dispatch(loadDirectory());
    return () => { cancelled = true; };
  }, [dispatch]);

  if (!meeting) {
    return (
      <PageContainer>
        <PageContent>
          <NoContent message="Meeting not found." />
        </PageContent>
      </PageContainer>
    );
  }

  const toggleAttendee = (upn: string) => {
    setAttendees((prev) => {
      const next = new Set(prev);
      if (next.has(upn)) next.delete(upn);
      else next.add(upn);
      return next;
    });
  };

  const save = async () => {
    if (!title.trim()) return;
    setSaving(true);
    setSaveError(undefined);
    try {
      // If this meeting came from Graph (has sourceIndex), patch through
      // the api/'s Graph PATCH endpoint. Otherwise just update Redux.
      const cleanLinks = links
        .map((l) => ({ label: l.label.trim(), url: l.url.trim() }))
        .filter((l) => l.url);
      if (typeof sourceIndex === 'number') {
        await (apiFactory() as any).meetings.update(meeting._id, {
          sourceIndex,
          typeSlug,
          title: title.trim(),
          agenda: agenda.trim(),
          location: location.trim(),
          startsAt,
          isOnlineMeeting,
          attendees: Array.from(attendees),
          links: cleanLinks,
        });
      }
      dispatch(
        updateMeeting({
          _id: meeting._id,
          title: title.trim(),
          agenda: agenda.trim(),
          location: location.trim(),
          startsAt,
          lat: coords?.lat,
          lng: coords?.lng,
          links: cleanLinks,
          ...(typeSlug ? { type: typeSlug } as any : {}),
        })
      );
      navigation.goBack();
    } catch (e: any) {
      setSaveError(e?.message ?? String(e));
    } finally {
      setSaving(false);
    }
  };

  const types = catalog.types;
  const sources = catalog.sources;
  const currentSource = sources.find((s) => s.index === sourceIndex);

  return (
    <PageContainer>
      <PageContent>
        <TextInput label="Title" value={title} onChangeText={setTitle} mode="outlined" style={{ marginBottom: 10 }} />

        {/* Type — editable; updating changes the event's Outlook category.
            Dropdown rather than chips so it reads as a form field (Edit
            screen has more state to scan than Create, where chips work). */}
        <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600', marginBottom: 6 }}>
          Meeting type
        </Text>
        {catalogError ? (
          <HelperText type="error" visible>Couldn't load meeting types: {catalogError}</HelperText>
        ) : null}
        {types.length === 0 && !catalogError ? (
          <ActivityIndicator style={{ marginVertical: 8 }} />
        ) : (
          (() => {
            const selectedType = types.find((t) => t.slug === typeSlug);
            return (
              <Menu
                visible={typeMenuOpen}
                onDismiss={() => setTypeMenuOpen(false)}
                anchor={
                  <TouchableOpacity
                    onPress={() => setTypeMenuOpen(true)}
                    activeOpacity={0.7}
                    onLayout={(e) => setTypeAnchorWidth(e.nativeEvent.layout.width)}
                  >
                    <View
                      style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                        backgroundColor: theme.colors.darkDefault,
                        borderWidth: 1,
                        borderColor: 'rgba(255,255,255,0.29)',
                        borderRadius: 4,
                        paddingHorizontal: 12,
                        paddingVertical: 10,
                        marginBottom: 12,
                      }}
                    >
                      <MaterialCommunityIcons
                        name={selectedType ? (TYPE_ICONS[selectedType.slug] ?? 'calendar') : 'calendar'}
                        size={18}
                        color={theme.colors.textDarker}
                        style={{ marginRight: 8 }}
                      />
                      <Text style={{ color: theme.colors.text, flex: 1 }}>
                        {selectedType?.displayName ?? 'Select type'}
                      </Text>
                      <MaterialCommunityIcons name="chevron-down" size={18} color={theme.colors.textDarker} />
                    </View>
                  </TouchableOpacity>
                }
                contentStyle={{
                  backgroundColor: theme.colors.darkDefault,
                  // Pin the dropdown to the anchor's measured width so the
                  // menu flush-aligns with the field instead of sizing to
                  // its widest title.
                  width: typeAnchorWidth,
                }}
              >
                {types.map((t) => {
                  const selected = t.slug === typeSlug;
                  return (
                    <Menu.Item
                      key={t.slug}
                      title={t.displayName}
                      leadingIcon={TYPE_ICONS[t.slug] ?? 'calendar'}
                      trailingIcon={selected ? 'check' : undefined}
                      onPress={() => {
                        setTypeSlug(t.slug);
                        setTypeMenuOpen(false);
                      }}
                      titleStyle={{
                        color: selected ? theme.colors.primary : theme.colors.text,
                        fontWeight: selected ? '700' : '400',
                      }}
                    />
                  );
                })}
              </Menu>
            );
          })()
        )}

        {/* Source — read-only on edit. Graph can't move events between
            calendars in a single PATCH. To change source, delete +
            reschedule. */}
        {currentSource ? (
          <>
            <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600', marginBottom: 6 }}>
              On calendar
            </Text>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 }}>
              <Chip
                icon="calendar-lock"
                style={{ marginRight: 8, marginBottom: 8, backgroundColor: theme.colors.secondary }}
                textStyle={{ color: theme.colors.text, fontSize: 12 }}
              >
                {currentSource.name}
              </Chip>
            </View>
            <HelperText type="info" visible style={{ marginLeft: -8, marginBottom: 4 }}>
              Source calendar can't change on edit. To move this meeting, delete it and reschedule.
            </HelperText>
          </>
        ) : null}

        <TextInput label="Location" value={location} onChangeText={setLocation} mode="outlined" style={{ marginBottom: 10 }} />
        {/* Map collapsed by default — admins can set a pin if they want
            one, but most meetings don't need one (the Location text
            field is enough). Address inside the picker is wired to the
            form's Location field so typing in either keeps both in
            sync, and "Find" geocodes it onto the map. */}
        <LocationPicker
          value={coords}
          onChange={setCoords}
          onClear={() => setCoords(undefined)}
          address={location}
          onAddressChange={setLocation}
        />
        <DateTimeField label="Date & time" value={startsAt} onChange={setStartsAt} />
        <TextInput label="Agenda" value={agenda} onChangeText={setAgenda} mode="outlined" multiline numberOfLines={4} style={{ marginBottom: 10 }} />

        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 10 }}>
          <Switch value={isOnlineMeeting} onValueChange={setIsOnlineMeeting} color={theme.colors.primary} />
          <Text style={{ color: theme.colors.text, marginLeft: 8 }}>Has a Teams join link</Text>
        </View>

        {/* Conference — read-only. Graph generates the Teams join URL /
            Meeting ID / Passcode automatically when isOnlineMeeting is
            on; we can't override them from the app. Shown here so the
            admin can confirm the values without leaving the form. */}
        {conference && (conference.joinUrl || conference.meetingId || conference.passcode) ? (
          <View
            style={{
              marginBottom: 12,
              padding: 12,
              backgroundColor: 'rgba(255,255,255,0.04)',
              borderRadius: 6,
              borderLeftWidth: 3,
              borderLeftColor: theme.colors.accent,
            }}
          >
            <Text style={{ color: theme.colors.text, fontSize: 13, fontWeight: '700' }}>
              📹  Microsoft Teams meeting
            </Text>
            {conference.joinUrl ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 6, fontSize: 12 }} numberOfLines={1}>
                🔗 {conference.joinUrl}
              </Text>
            ) : null}
            {conference.meetingId ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 2, fontSize: 12 }}>
                🆔 {conference.meetingId}
              </Text>
            ) : null}
            {conference.passcode ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 2, fontSize: 12 }}>
                🔒 {conference.passcode}
              </Text>
            ) : null}
            <HelperText type="info" visible style={{ marginLeft: -8, marginTop: 4 }}>
              Teams details are managed by Microsoft 365. Toggle "Has a Teams join link" off to remove them.
            </HelperText>
          </View>
        ) : null}

        {/* Links — editable. Saved as a "Links:" section in the event
            body so Graph round-trips them. Each row is a {label, url}. */}
        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
          <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600' }}>
            🔗  Links
          </Text>
          <Button compact mode="text" icon="plus" textColor={theme.colors.primary} onPress={addLink} style={{ marginLeft: 4 }}>
            Add link
          </Button>
        </View>
        {links.length === 0 ? (
          <HelperText type="info" visible style={{ marginLeft: -8, marginBottom: 8 }}>
            Optional. Add agendas, supporting documents, or any URL members should have handy.
          </HelperText>
        ) : null}
        {links.map((l, i) => (
          <View key={i} style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
            <TextInput
              dense mode="outlined" label="Label" value={l.label}
              onChangeText={(v) => updateLink(i, { label: v })}
              style={{ width: 140, marginRight: 6 }}
            />
            <TextInput
              dense mode="outlined" label="URL" value={l.url}
              onChangeText={(v) => updateLink(i, { url: v })}
              style={{ flex: 1, marginRight: 6 }}
              autoCapitalize="none"
              keyboardType="url"
            />
            <IconButton
              icon="close" size={18}
              iconColor={theme.colors.textDarker}
              onPress={() => removeLink(i)}
            />
          </View>
        ))}

        {/* Attendees — prefilled from the current event */}
        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
          <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600' }}>
            Invitees ({attendees.size})
          </Text>
          <Button
            mode="text"
            compact
            onPress={() => {
              const pred = defaultAudienceFor(typeSlug);
              setAttendees(new Set(licensedUsers.filter(pred).map((m: any) => m.upn.toLowerCase())));
            }}
            textColor={theme.colors.textDarker}
            style={{ marginLeft: 4 }}
          >
            Reset to type default
          </Button>
        </View>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginBottom: 12 }}>
          {licensedUsers
            .slice()
            .sort((a: any, b: any) => (a.name ?? '').localeCompare(b.name ?? ''))
            .map((m: any) => {
              const on = attendees.has(m.upn.toLowerCase());
              return (
                <Chip
                  key={m._id}
                  selected={on}
                  showSelectedCheck
                  onPress={() => toggleAttendee(m.upn.toLowerCase())}
                  style={{
                    marginRight: 6,
                    marginBottom: 6,
                    backgroundColor: on ? theme.colors.primary : theme.colors.secondary,
                  }}
                  textStyle={{ color: on ? '#000' : theme.colors.text, fontSize: 11 }}
                >
                  {m.name}
                </Chip>
              );
            })}
        </View>

        {saveError ? <HelperText type="error" visible>{saveError}</HelperText> : null}

        <Button
          mode="contained"
          onPress={save}
          disabled={!title.trim() || saving}
          buttonColor={theme.colors.primary}
          textColor="#000"
          style={{ marginTop: 8 }}
        >
          {saving ? 'Saving to Microsoft 365…' : 'Save changes'}
        </Button>
        <Text style={{ color: theme.colors.textDarker, fontSize: 12, marginTop: 8 }}>
          Changes to title, type, date/time, location, agenda, Teams link, and attendees are PATCHed to the underlying M365 calendar event.
        </Text>
      </PageContent>
    </PageContainer>
  );
}
