import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, TouchableOpacity, View } from 'react-native';
import { Button, Chip, Divider, HelperText, IconButton, Menu, Modal, Portal, Switch, Text, TextInput } from 'react-native-paper';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import moment from 'moment';
import { PageContainer, PageContent, NoContent, DateTimeField, LocationPicker, LatLng } from 'skintyee/components/layout';
import { useAppDispatch, useAppSelector } from 'skintyee/store';
import { loadDirectory } from 'skintyee/store/modules/directory';
import { updateMeeting } from 'skintyee/store/modules/meetings';
import { apiFactory } from 'skintyee/store/apis';
import { MeetingLink } from 'skintyee/models';
import { theme } from 'skintyee/styles';

// Admin: edit an existing band meeting. Matches the CreateMeeting form
// field-for-field (type chip / source chip / title / location / time /
// agenda / Teams toggle / attendees) so the experience is consistent.
//
// Source is read-only — Graph can't move events between calendars in
// a single PATCH (would require delete+recreate). If you need to move
// an event to a different calendar, delete this one and reschedule.
//
// Saves go through PATCH /v1/meetings/:id which calls Graph PATCH
// against the event's calendar path (derived from sourceIndex).

interface MeetingType { slug: string; displayName: string; category: string; description: string }
interface MeetingSource { index: number; kind: 'me'|'user'|'group'; name: string; upn?: string; groupId?: string }

const TYPE_ICONS: Record<string, string> = {
  'band-meeting':    'account-group',
  'council-meeting': 'gavel',
  'staff-meeting':   'briefcase',
  'public-event':    'star',
  'closed-session':  'lock',
};

function defaultAudienceFor(typeSlug: string): (m: any) => boolean {
  switch (typeSlug) {
    case 'band-meeting':
    case 'public-event':
      return (m) => m.accountType === 'licensed-user';
    case 'council-meeting':
    case 'closed-session':
      return (m) => m.accountType === 'licensed-user' && (m.bandGroups ?? []).includes('council');
    case 'staff-meeting':
      return (m) => m.accountType === 'licensed-user' && (m.bandGroups ?? []).includes('management');
    default:
      return (m) => m.accountType === 'licensed-user';
  }
}

export default function EditMeeting({ route, navigation }: any) {
  const dispatch = useAppDispatch();
  const id = route?.params?.id;
  const meeting = useAppSelector((s) => s.meetings.entities.find((m: any) => m._id === id));

  // Form state — initialized from the existing meeting
  const [title, setTitle] = useState(meeting?.title ?? '');
  const [location, setLocation] = useState(meeting?.location ?? '');
  const [coords, setCoords] = useState<LatLng | undefined>(
    meeting?.lat != null && meeting?.lng != null ? { lat: meeting.lat, lng: meeting.lng } : undefined
  );
  const [startsAt, setStartsAt] = useState((meeting as any)?.startsAt ?? moment().toISOString());
  const [agenda, setAgenda] = useState(meeting?.agenda ?? '');
  const [typeSlug, setTypeSlug] = useState<string>((meeting as any)?.type ?? 'band-meeting');
  const sourceIndex: number | undefined = (meeting as any)?.sourceIndex;
  const [isOnlineMeeting, setIsOnlineMeeting] = useState<boolean>((meeting as any)?.isOnlineMeeting ?? false);
  // Editable "Links:" section — round-trips through Graph as plain
  // text appended to the body. Conference details (Teams join URL,
  // meeting ID, passcode) are auto-generated by Graph when
  // isOnlineMeeting=true, so they're shown read-only further down.
  const [links, setLinks] = useState<MeetingLink[]>(((meeting as any)?.links ?? []) as MeetingLink[]);
  const conference = (meeting as any)?.conference as undefined | { joinUrl?: string; meetingId?: string; passcode?: string; helpUrl?: string };

  const addLink = () => setLinks((prev) => [...prev, { label: '', url: '' }]);
  const updateLink = (i: number, patch: Partial<MeetingLink>) =>
    setLinks((prev) => prev.map((l, idx) => (idx === i ? { ...l, ...patch } : l)));
  const removeLink = (i: number) =>
    setLinks((prev) => prev.filter((_, idx) => idx !== i));

  const [catalog, setCatalog] = useState<{ types: MeetingType[]; sources: MeetingSource[] }>({ types: [], sources: [] });
  const [catalogError, setCatalogError] = useState<string | undefined>();
  const [typeMenuOpen, setTypeMenuOpen] = useState(false);
  // Invitees modal — opens a searchable directory + custom-email
  // add field. The form below just shows a compact summary of the
  // currently-selected invitees with inline remove.
  const [inviteesModalOpen, setInviteesModalOpen] = useState(false);
  const [inviteeSearch, setInviteeSearch] = useState('');
  const [customEmail, setCustomEmail] = useState('');
  const [customEmailError, setCustomEmailError] = useState<string | undefined>();
  // Anchor width captured via onLayout so the dropdown's content
  // matches the field's width instead of sizing to its widest item.
  const [typeAnchorWidth, setTypeAnchorWidth] = useState<number | undefined>();
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | undefined>();

  // Attendees prefilled from the existing event's attendees[]
  const directory = useAppSelector((s) => s.directory.entities);
  const licensedUsers = useMemo(
    () => directory.filter((m: any) => m.accountType === 'licensed-user' && m.upn),
    [directory]
  );
  const initialAttendeesKey = JSON.stringify((meeting as any)?.attendees ?? []);
  const [attendees, setAttendees] = useState<Set<string>>(
    new Set(((meeting as any)?.attendees ?? []).map((a: any) => (a.upn ?? '').toLowerCase()).filter(Boolean))
  );
  useEffect(() => {
    setAttendees(new Set(
      ((meeting as any)?.attendees ?? []).map((a: any) => (a.upn ?? '').toLowerCase()).filter(Boolean)
    ));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialAttendeesKey]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const r = await (apiFactory() as any).meetings.types();
        if (!cancelled) setCatalog(r);
      } catch (e: any) {
        if (!cancelled) setCatalogError(e?.message ?? String(e));
      }
    })();
    dispatch(loadDirectory());
    return () => { cancelled = true; };
  }, [dispatch]);

  if (!meeting) {
    return (
      <PageContainer>
        <PageContent>
          <NoContent message="Meeting not found." />
        </PageContent>
      </PageContainer>
    );
  }

  const toggleAttendee = (upn: string) => {
    setAttendees((prev) => {
      const next = new Set(prev);
      if (next.has(upn)) next.delete(upn);
      else next.add(upn);
      return next;
    });
  };

  // Look up a friendly display name for a UPN we've added — falls back
  // to the email when the entry isn't in the directory (i.e. it was a
  // custom-email add).
  const inviteeName = (upn: string): string => {
    const m = directory.find((m: any) => (m.upn ?? '').toLowerCase() === upn);
    return (m as any)?.name ?? upn;
  };

  // ASCII email-ish check — Graph itself rejects bad addresses on PATCH,
  // but a quick gate keeps the picker from accumulating obvious typos.
  const isValidEmail = (s: string): boolean => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);

  const addCustomEmail = () => {
    const e = customEmail.trim().toLowerCase();
    if (!e) return;
    if (!isValidEmail(e)) {
      setCustomEmailError('Enter a valid email address.');
      return;
    }
    setAttendees((prev) => new Set(prev).add(e));
    setCustomEmail('');
    setCustomEmailError(undefined);
  };

  // Members matching the search box. Empty query → full list.
  const filteredMembers = useMemo(() => {
    const q = inviteeSearch.trim().toLowerCase();
    const sorted = licensedUsers.slice().sort((a: any, b: any) => (a.name ?? '').localeCompare(b.name ?? ''));
    if (!q) return sorted;
    return sorted.filter((m: any) =>
      (m.name ?? '').toLowerCase().includes(q) || (m.upn ?? '').toLowerCase().includes(q)
    );
  }, [licensedUsers, inviteeSearch]);

  // UPNs in the attendees set that don't match any directory entry —
  // these are the custom-emails added by the admin. Surface them at the
  // top of the modal list so they're easy to remove.
  const customAttendees = useMemo(() => {
    const directoryUpns = new Set(licensedUsers.map((m: any) => (m.upn ?? '').toLowerCase()));
    return Array.from(attendees).filter((upn) => !directoryUpns.has(upn));
  }, [attendees, licensedUsers]);

  const save = async () => {
    if (!title.trim()) return;
    setSaving(true);
    setSaveError(undefined);
    try {
      // If this meeting came from Graph (has sourceIndex), patch through
      // the api/'s Graph PATCH endpoint. Otherwise just update Redux.
      const cleanLinks = links
        .map((l) => ({ label: l.label.trim(), url: l.url.trim() }))
        .filter((l) => l.url);
      if (typeof sourceIndex === 'number') {
        await (apiFactory() as any).meetings.update(meeting._id, {
          sourceIndex,
          typeSlug,
          title: title.trim(),
          agenda: agenda.trim(),
          location: location.trim(),
          startsAt,
          isOnlineMeeting,
          attendees: Array.from(attendees),
          links: cleanLinks,
        });
      }
      dispatch(
        updateMeeting({
          _id: meeting._id,
          title: title.trim(),
          agenda: agenda.trim(),
          location: location.trim(),
          startsAt,
          lat: coords?.lat,
          lng: coords?.lng,
          links: cleanLinks,
          ...(typeSlug ? { type: typeSlug } as any : {}),
        })
      );
      navigation.goBack();
    } catch (e: any) {
      setSaveError(e?.message ?? String(e));
    } finally {
      setSaving(false);
    }
  };

  const types = catalog.types;
  const sources = catalog.sources;
  const currentSource = sources.find((s) => s.index === sourceIndex);

  return (
    <PageContainer>
      <PageContent>
        <TextInput label="Title" value={title} onChangeText={setTitle} mode="outlined" style={{ marginBottom: 10 }} />

        {/* Type — editable; updating changes the event's Outlook category.
            Dropdown rather than chips so it reads as a form field (Edit
            screen has more state to scan than Create, where chips work). */}
        <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600', marginBottom: 6 }}>
          Meeting type
        </Text>
        {catalogError ? (
          <HelperText type="error" visible>Couldn't load meeting types: {catalogError}</HelperText>
        ) : null}
        {types.length === 0 && !catalogError ? (
          <ActivityIndicator style={{ marginVertical: 8 }} />
        ) : (
          (() => {
            const selectedType = types.find((t) => t.slug === typeSlug);
            return (
              <Menu
                visible={typeMenuOpen}
                onDismiss={() => setTypeMenuOpen(false)}
                anchor={
                  <TouchableOpacity
                    onPress={() => setTypeMenuOpen(true)}
                    activeOpacity={0.7}
                    onLayout={(e) => setTypeAnchorWidth(e.nativeEvent.layout.width)}
                  >
                    <View
                      style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                        backgroundColor: theme.colors.darkDefault,
                        borderWidth: 1,
                        borderColor: 'rgba(255,255,255,0.29)',
                        borderRadius: 4,
                        paddingHorizontal: 12,
                        paddingVertical: 10,
                        marginBottom: 12,
                      }}
                    >
                      <MaterialCommunityIcons
                        name={selectedType ? (TYPE_ICONS[selectedType.slug] ?? 'calendar') : 'calendar'}
                        size={18}
                        color={theme.colors.textDarker}
                        style={{ marginRight: 8 }}
                      />
                      <Text style={{ color: theme.colors.text, flex: 1 }}>
                        {selectedType?.displayName ?? 'Select type'}
                      </Text>
                      <MaterialCommunityIcons name="chevron-down" size={18} color={theme.colors.textDarker} />
                    </View>
                  </TouchableOpacity>
                }
                contentStyle={{
                  backgroundColor: theme.colors.darkDefault,
                  // Pin the dropdown to the anchor's measured width so the
                  // menu flush-aligns with the field instead of sizing to
                  // its widest title.
                  width: typeAnchorWidth,
                }}
              >
                {types.map((t) => {
                  const selected = t.slug === typeSlug;
                  return (
                    <Menu.Item
                      key={t.slug}
                      title={t.displayName}
                      leadingIcon={TYPE_ICONS[t.slug] ?? 'calendar'}
                      trailingIcon={selected ? 'check' : undefined}
                      onPress={() => {
                        setTypeSlug(t.slug);
                        setTypeMenuOpen(false);
                      }}
                      titleStyle={{
                        color: selected ? theme.colors.primary : theme.colors.text,
                        fontWeight: selected ? '700' : '400',
                      }}
                    />
                  );
                })}
              </Menu>
            );
          })()
        )}

        {/* Source — read-only on edit. Graph can't move events between
            calendars in a single PATCH. To change source, delete +
            reschedule. */}
        {currentSource ? (
          <>
            <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600', marginBottom: 6 }}>
              On calendar
            </Text>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 }}>
              <Chip
                icon="calendar-lock"
                style={{ marginRight: 8, marginBottom: 8, backgroundColor: theme.colors.secondary }}
                textStyle={{ color: theme.colors.text, fontSize: 12 }}
              >
                {currentSource.name}
              </Chip>
            </View>
            <HelperText type="info" visible style={{ marginLeft: -8, marginBottom: 4 }}>
              Source calendar can't change on edit. To move this meeting, delete it and reschedule.
            </HelperText>
          </>
        ) : null}

        <TextInput label="Location" value={location} onChangeText={setLocation} mode="outlined" style={{ marginBottom: 10 }} />
        {/* Map collapsed by default — admins can set a pin if they want
            one, but most meetings don't need one (the Location text
            field is enough). Address inside the picker is wired to the
            form's Location field so typing in either keeps both in
            sync, and "Find" geocodes it onto the map. */}
        <LocationPicker
          value={coords}
          onChange={setCoords}
          onClear={() => setCoords(undefined)}
          address={location}
          onAddressChange={setLocation}
        />
        <DateTimeField label="Date & time" value={startsAt} onChange={setStartsAt} />
        <TextInput label="Agenda" value={agenda} onChangeText={setAgenda} mode="outlined" multiline numberOfLines={4} style={{ marginBottom: 10 }} />

        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 10 }}>
          <Switch value={isOnlineMeeting} onValueChange={setIsOnlineMeeting} color={theme.colors.primary} />
          <Text style={{ color: theme.colors.text, marginLeft: 8 }}>Has a Teams join link</Text>
        </View>

        {/* Conference — read-only. Graph generates the Teams join URL /
            Meeting ID / Passcode automatically when isOnlineMeeting is
            on; we can't override them from the app. Shown here so the
            admin can confirm the values without leaving the form. */}
        {conference && (conference.joinUrl || conference.meetingId || conference.passcode) ? (
          <View
            style={{
              marginBottom: 12,
              padding: 12,
              backgroundColor: 'rgba(255,255,255,0.04)',
              borderRadius: 6,
              borderLeftWidth: 3,
              borderLeftColor: theme.colors.accent,
            }}
          >
            <Text style={{ color: theme.colors.text, fontSize: 13, fontWeight: '700' }}>
              📹  Microsoft Teams meeting
            </Text>
            {conference.joinUrl ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 6, fontSize: 12 }} numberOfLines={1}>
                🔗 {conference.joinUrl}
              </Text>
            ) : null}
            {conference.meetingId ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 2, fontSize: 12 }}>
                🆔 {conference.meetingId}
              </Text>
            ) : null}
            {conference.passcode ? (
              <Text style={{ color: theme.colors.textDarker, marginTop: 2, fontSize: 12 }}>
                🔒 {conference.passcode}
              </Text>
            ) : null}
            <HelperText type="info" visible style={{ marginLeft: -8, marginTop: 4 }}>
              Teams details are managed by Microsoft 365. Toggle "Has a Teams join link" off to remove them.
            </HelperText>
          </View>
        ) : null}

        {/* Links — editable. Saved as a "Links:" section in the event
            body so Graph round-trips them. Each row is a {label, url}. */}
        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
          <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600' }}>
            🔗  Links
          </Text>
          <Button compact mode="text" icon="plus" textColor={theme.colors.primary} onPress={addLink} style={{ marginLeft: 4 }}>
            Add link
          </Button>
        </View>
        {links.length === 0 ? (
          <HelperText type="info" visible style={{ marginLeft: -8, marginBottom: 8 }}>
            Optional. Add agendas, supporting documents, or any URL members should have handy.
          </HelperText>
        ) : null}
        {links.map((l, i) => (
          <View key={i} style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
            <TextInput
              dense mode="outlined" label="Label" value={l.label}
              onChangeText={(v) => updateLink(i, { label: v })}
              style={{ width: 140, marginRight: 6 }}
            />
            <TextInput
              dense mode="outlined" label="URL" value={l.url}
              onChangeText={(v) => updateLink(i, { url: v })}
              style={{ flex: 1, marginRight: 6 }}
              autoCapitalize="none"
              keyboardType="url"
            />
            <IconButton
              icon="close" size={18}
              iconColor={theme.colors.textDarker}
              onPress={() => removeLink(i)}
            />
          </View>
        ))}

        {/* Attendees — prefilled from the current event */}
        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 6 }}>
          <Text style={{ color: theme.colors.text, fontSize: 14, fontWeight: '600' }}>
            Invitees ({attendees.size})
          </Text>
          <Button
            mode="text"
            compact
            onPress={() => {
              const pred = defaultAudienceFor(typeSlug);
              setAttendees(new Set(licensedUsers.filter(pred).map((m: any) => m.upn.toLowerCase())));
            }}
            textColor={theme.colors.textDarker}
            style={{ marginLeft: 4 }}
          >
            Reset to type default
          </Button>
        </View>
        {/* Compact summary of currently-selected invitees. Tap × on a
            chip to remove inline, or tap "Manage" to open the modal. */}
        {attendees.size === 0 ? (
          <HelperText type="info" visible style={{ marginLeft: -8, marginBottom: 6 }}>
            No invitees yet.
          </HelperText>
        ) : (
          <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginBottom: 6 }}>
            {Array.from(attendees).map((upn) => (
              <Chip
                key={upn}
                compact
                closeIcon="close"
                onClose={() => toggleAttendee(upn)}
                style={{ marginRight: 6, marginBottom: 6, backgroundColor: theme.colors.primary }}
                textStyle={{ color: '#000', fontSize: 11 }}
              >
                {inviteeName(upn)}
              </Chip>
            ))}
          </View>
        )}
        <Button
          mode="outlined" icon="account-multiple-plus"
          textColor={theme.colors.text}
          onPress={() => setInviteesModalOpen(true)}
          style={{ alignSelf: 'flex-start', marginBottom: 12 }}
        >
          Manage invitees
        </Button>

        {saveError ? <HelperText type="error" visible>{saveError}</HelperText> : null}

        <Button
          mode="contained"
          onPress={save}
          disabled={!title.trim() || saving}
          buttonColor={theme.colors.primary}
          textColor="#000"
          style={{ marginTop: 8 }}
        >
          {saving ? 'Saving to Microsoft 365…' : 'Save changes'}
        </Button>
        <Text style={{ color: theme.colors.textDarker, fontSize: 12, marginTop: 8 }}>
          Changes to title, type, date/time, location, agenda, Teams link, and attendees are PATCHed to the underlying M365 calendar event.
        </Text>

        {/* Invitees modal — search the directory or paste in a custom
            email. The chip strip outside the modal is the persisted
            summary; closing the modal doesn't reset anything (the
            attendees Set is the canonical state). */}
        <Portal>
          <Modal
            visible={inviteesModalOpen}
            onDismiss={() => setInviteesModalOpen(false)}
            contentContainerStyle={{
              backgroundColor: theme.colors.darkDefault,
              marginHorizontal: 20,
              borderRadius: 8,
              maxHeight: '85%',
              alignSelf: 'center',
              width: '90%',
              maxWidth: 520,
            }}
          >
            {/* Header */}
            <View style={{ flexDirection: 'row', alignItems: 'center', padding: 12, paddingBottom: 6 }}>
              <Text style={{ color: theme.colors.text, fontSize: 16, fontWeight: '700', flex: 1 }}>
                Manage invitees ({attendees.size})
              </Text>
              <IconButton icon="close" size={20} iconColor={theme.colors.textDarker} onPress={() => setInviteesModalOpen(false)} />
            </View>
            <Divider style={{ backgroundColor: 'rgba(255,255,255,0.1)' }} />

            <ScrollView style={{ paddingHorizontal: 12 }}>
              {/* Add custom email */}
              <Text style={{ color: theme.colors.textDarker, fontSize: 11, letterSpacing: 1, marginTop: 12 }}>
                ADD BY EMAIL
              </Text>
              <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 6 }}>
                <TextInput
                  dense mode="outlined"
                  label="email@example.com"
                  value={customEmail}
                  onChangeText={(v) => { setCustomEmail(v); setCustomEmailError(undefined); }}
                  onSubmitEditing={addCustomEmail}
                  returnKeyType="done"
                  style={{ flex: 1, marginRight: 6 }}
                  autoCapitalize="none"
                  keyboardType="email-address"
                  error={!!customEmailError}
                />
                <Button
                  compact mode="contained" icon="plus"
                  buttonColor={theme.colors.primary} textColor="#000"
                  onPress={addCustomEmail}
                  disabled={!customEmail.trim()}
                >
                  Add
                </Button>
              </View>
              {customEmailError ? (
                <HelperText type="error" visible style={{ marginLeft: -8 }}>{customEmailError}</HelperText>
              ) : null}

              {/* Custom emails currently in the attendees set */}
              {customAttendees.length > 0 ? (
                <>
                  <Text style={{ color: theme.colors.textDarker, fontSize: 11, letterSpacing: 1, marginTop: 14 }}>
                    CUSTOM ({customAttendees.length})
                  </Text>
                  <View style={{ marginTop: 6 }}>
                    {customAttendees.map((upn) => (
                      <TouchableOpacity
                        key={upn}
                        onPress={() => toggleAttendee(upn)}
                        style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 8 }}
                      >
                        <MaterialCommunityIcons name="email" size={18} color={theme.colors.textDarker} style={{ marginRight: 10 }} />
                        <Text style={{ color: theme.colors.text, flex: 1, fontSize: 13 }}>{upn}</Text>
                        <MaterialCommunityIcons name="close" size={18} color={theme.colors.textDarker} />
                      </TouchableOpacity>
                    ))}
                  </View>
                </>
              ) : null}

              {/* Search + member list */}
              <Text style={{ color: theme.colors.textDarker, fontSize: 11, letterSpacing: 1, marginTop: 14 }}>
                DIRECTORY
              </Text>
              <TextInput
                dense mode="outlined"
                label="Search members"
                value={inviteeSearch}
                onChangeText={setInviteeSearch}
                style={{ marginTop: 6, marginBottom: 6 }}
                autoCapitalize="none"
                left={<TextInput.Icon icon="magnify" />}
                right={inviteeSearch ? <TextInput.Icon icon="close" onPress={() => setInviteeSearch('')} /> : undefined}
              />
              {filteredMembers.length === 0 ? (
                <HelperText type="info" visible style={{ marginLeft: -8 }}>
                  No matches.
                </HelperText>
              ) : null}
              {filteredMembers.map((m: any) => {
                const upn = (m.upn ?? '').toLowerCase();
                const on = attendees.has(upn);
                return (
                  <TouchableOpacity
                    key={m._id}
                    onPress={() => toggleAttendee(upn)}
                    style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 8 }}
                  >
                    <MaterialCommunityIcons
                      name={on ? 'checkbox-marked' : 'checkbox-blank-outline'}
                      size={20}
                      color={on ? theme.colors.primary : theme.colors.textDarker}
                      style={{ marginRight: 10 }}
                    />
                    <View style={{ flex: 1 }}>
                      <Text style={{ color: theme.colors.text, fontSize: 13 }}>{m.name}</Text>
                      <Text style={{ color: theme.colors.textDarker, fontSize: 11 }}>{m.upn}</Text>
                    </View>
                  </TouchableOpacity>
                );
              })}

              <View style={{ height: 12 }} />
            </ScrollView>

            <Divider style={{ backgroundColor: 'rgba(255,255,255,0.1)' }} />
            <View style={{ padding: 12, flexDirection: 'row', justifyContent: 'flex-end' }}>
              <Button
                mode="contained"
                buttonColor={theme.colors.primary} textColor="#000"
                onPress={() => setInviteesModalOpen(false)}
              >
                Done
              </Button>
            </View>
          </Modal>
        </Portal>
      </PageContent>
    </PageContainer>
  );
}
