import sys, zlib, base64, struct

SRC = "app/assets/skintyee-logo.png"
OUT = "api/src/timesheet-logo.ts"
MAX_W = 200  # downscale cap (keeps PDF small; still crisp for a header)

data = open(SRC, "rb").read()
assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
pos = 8
width = height = bitdepth = colortype = interlace = None
idat = b""
while pos < len(data):
    ln = struct.unpack(">I", data[pos:pos+4])[0]; typ = data[pos+4:pos+8]
    chunk = data[pos+8:pos+8+ln]; pos += 12 + ln
    if typ == b"IHDR":
        width, height, bitdepth, colortype, _comp, _filt, interlace = struct.unpack(">IIBBBBB", chunk)
    elif typ == b"IDAT":
        idat += chunk
    elif typ == b"IEND":
        break
print(f"IHDR {width}x{height} depth={bitdepth} colortype={colortype} interlace={interlace}")
assert bitdepth == 8 and interlace == 0, "only 8-bit non-interlaced supported"
channels = {0:1, 2:3, 3:1, 4:2, 6:4}[colortype]
raw = zlib.decompress(idat)
stride = width * channels

# Reverse PNG line filters → flat pixel buffer
def paeth(a,b,c):
    p=a+b-c; pa=abs(p-a); pb=abs(p-b); pc=abs(p-c)
    return a if (pa<=pb and pa<=pc) else (b if pb<=pc else c)
out = bytearray(width*height*channels)
prev = bytearray(stride)
o = 0
for y in range(height):
    ft = raw[o]; o += 1
    line = bytearray(raw[o:o+stride]); o += stride
    for i in range(stride):
        a = line[i-channels] if i>=channels else 0
        b = prev[i]
        c = prev[i-channels] if i>=channels else 0
        if   ft==1: line[i]=(line[i]+a)&0xff
        elif ft==2: line[i]=(line[i]+b)&0xff
        elif ft==3: line[i]=(line[i]+((a+b)>>1))&0xff
        elif ft==4: line[i]=(line[i]+paeth(a,b,c))&0xff
    out[y*stride:(y+1)*stride]=line
    prev=line

def px(x,y):
    i=(y*width+x)*channels
    if channels==4: return (out[i],out[i+1],out[i+2],out[i+3])
    if channels==3: return (out[i],out[i+1],out[i+2],255)
    if channels==2: return (out[i],out[i],out[i],out[i+1])
    return (out[i],out[i],out[i],255)

# Downscale (nearest) + composite over white → RGB
import math
scale = min(1.0, MAX_W/width)
ow, oh = max(1,round(width*scale)), max(1,round(height*scale))
rgb = bytearray(ow*oh*3)
k=0
for y in range(oh):
    sy=min(height-1, int(y/scale))
    for x in range(ow):
        sx=min(width-1, int(x/scale))
        r,g,b,a=px(sx,sy)
        af=a/255.0
        rgb[k]  =round(r*af+255*(1-af)); rgb[k+1]=round(g*af+255*(1-af)); rgb[k+2]=round(b*af+255*(1-af))
        k+=3
comp = zlib.compress(bytes(rgb), 9)
b64 = base64.b64encode(comp).decode()
ts = (
    "// AUTO-GENERATED by scripts/gen-timesheet-logo.py — do not edit by hand.\n"
    "// Skin Tyee logo, composited on white, as a zlib/FlateDecode DeviceRGB image\n"
    "// stream (base64). Baked into source so it ships in dist/ with no binary asset.\n"
    f"export const TIMESHEET_LOGO = {{\n"
    f"  widthPx: {ow},\n  heightPx: {oh},\n"
    f"  /** zlib-deflated raw RGB (8 bpc), base64. */\n"
    f"  flateRgbB64:\n    '{b64}',\n"
    f"}};\n"
)
open(OUT,"w").write(ts)
print(f"out {ow}x{oh}  deflated={len(comp)}B  base64={len(b64)}B  -> {OUT}")
