/**
 * End-to-end smoke test for every catalogued source.
 *
 * For each source:
 *   1. Run the scrape (or compute the search URL for link-only).
 *   2. Open the resulting search URL in puppeteer and take a screenshot.
 *   3. Emit a markdown report at test/results/E2E.md with the per-source
 *      verdict, sample items, and an embedded screenshot.
 *
 * Run:
 *   pnpm --filter @skintyee/lookup-api test:e2e
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ALL_SOURCES } from '../src/sources/index.js';
import type { ScrapeResult, Source } from '../src/types.js';
import { closeBrowser, withPage } from '../src/util/puppet.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, 'results');
const SHOT_DIR = join(OUT_DIR, 'screenshots');
const REPORT_PATH = join(OUT_DIR, 'E2E.md');

// Known-good queries — chosen because we've verified at least one live hit at
// development time. If a scraper regresses (zero items), this surfaces it.
const QUERIES: Record<string, string> = {
  'orgbook-bc': 'Birdco',
  mras: 'Two Worlds Consulting',
  website: 'Birdco Industrial Resources Ltd',
  'bc-indigenous-listings': 'consulting',
  // "Cambium" hits one IBD entry (Cambium Indigenous Professional Services).
  'isc-ibd': 'Cambium',
  ccab: 'consulting',
  'fn-fma': 'Tsleil',
  'fn-profiles': 'Skin Tyee',
  'open-canada-contracts': 'First Nation',
  'open-canada-grants': 'First Nation',
  'open-canada-ckan': 'Indigenous',
  'bc-open-data-ckan': 'Indigenous',
  merx: 'First Nation',
};

interface Result {
  id: string;
  name: string;
  scrapable: boolean;
  category: string;
  query: string;
  status: 'pass' | 'fail';
  detail: string;
  items: Array<{ title: string; subtitle?: string; url?: string; snippet?: string }>;
  searchUrl: string;
  screenshotPath?: string;
  durationMs: number;
}

async function captureScreenshot(url: string, dest: string): Promise<void> {
  if (!/^https?:\/\//.test(url)) return;
  // Skip direct file downloads (CSV/zip/etc.) — puppeteer hangs trying to render
  // a multi-megabyte download.
  if (/\.(csv|zip|xlsx?|pdf)(\?|$)/i.test(url)) return;
  await withPage(async (page) => {
    await page.goto(url, { waitUntil: 'networkidle2', timeout: 25000 });
    // Settle for any JS-rendered content.
    await new Promise((r) => setTimeout(r, 1500));
    await page.screenshot({ path: dest, fullPage: false, type: 'png' });
  }, { timeoutMs: 30000 }).catch(() => {});
}

async function runOne(s: Source): Promise<Result> {
  const start = Date.now();
  const q = QUERIES[s.id] ?? 'Indigenous';
  const opts = {
    indigenousOnly: false,
    website: s.id === 'website' ? 'https://birdcoirl.ca' : undefined,
  };

  let items: Result['items'] = [];
  let searchUrl = '';
  let status: Result['status'] = 'pass';
  let detail = '';

  try {
    if (s.scrape) {
      const res: ScrapeResult = await s.scrape(q, opts);
      items = res.items;
      searchUrl = res.searchUrl;
      const ok = items.length > 0;
      status = ok ? 'pass' : 'fail';
      detail = ok ? `${items.length} items` : 'returned 0 items';
    } else {
      searchUrl = s.searchUrl(q, opts);
      const okUrl = /^https?:\/\//.test(searchUrl);
      status = okUrl ? 'pass' : 'fail';
      detail = okUrl ? 'link only — search URL emitted' : `bad URL: ${searchUrl}`;
    }
  } catch (err) {
    status = 'fail';
    detail = `error: ${(err as Error).message}`;
  }

  // Screenshot the search URL (skip for the company-website source — it's
  // already the target site itself, but capturing it is still informative).
  const screenshotPath = join(SHOT_DIR, `${s.id}.png`);
  if (/^https?:\/\//.test(searchUrl)) {
    await captureScreenshot(searchUrl, screenshotPath);
  }

  return {
    id: s.id,
    name: s.name,
    scrapable: !!s.scrape,
    category: s.category,
    query: q,
    status,
    detail,
    items,
    searchUrl,
    screenshotPath,
    durationMs: Date.now() - start,
  };
}

function pad(s: string, n: number) { return s + ' '.repeat(Math.max(0, n - s.length)); }
const G = (s: string) => `\x1b[32m${s}\x1b[0m`;
const R = (s: string) => `\x1b[31m${s}\x1b[0m`;
const D = (s: string) => `\x1b[2m${s}\x1b[0m`;

async function writeReport(results: Result[], totalDurationMs: number): Promise<void> {
  await mkdir(SHOT_DIR, { recursive: true });
  const pass = results.filter((r) => r.status === 'pass').length;
  const fail = results.length - pass;
  const passedAt = new Date();

  const lines: string[] = [];
  lines.push(`# Skin Tyee Lookup — End-to-end test results`);
  lines.push('');
  lines.push(`**Run:** ${passedAt.toISOString()} · **Total time:** ${(totalDurationMs / 1000).toFixed(1)}s · **Result:** ${pass}/${results.length} pass${fail ? `, ${fail} fail` : ''}`);
  lines.push('');
  lines.push(`> Auto-generated by \`pnpm --filter @skintyee/lookup-api test:e2e\`. Don't edit by hand — the next run overwrites this file.`);
  lines.push('');
  lines.push(`## Summary`);
  lines.push('');
  lines.push(`| # | Source | Mode | Strategy | Query | Status | Result |`);
  lines.push(`|---|---|---|---|---|:---:|---|`);
  for (const r of results) {
    const src = ALL_SOURCES.find((s) => s.id === r.id);
    const mode = src?.mode ?? '?';
    const strategy = r.scrapable ? 'scrape' : 'link';
    const verdict = r.status === 'pass' ? '✅' : '❌';
    lines.push(`| ${results.indexOf(r) + 1} | **${r.name}** | ${mode} | ${strategy} | \`${r.query}\` | ${verdict} | ${r.detail} (${r.durationMs}ms) |`);
  }
  lines.push('');

  lines.push(`## Per-source proof`);
  lines.push('');
  for (const r of results) {
    lines.push(`### ${r.name}`);
    lines.push('');
    lines.push(`- **Source id:** \`${r.id}\` · **Category:** ${r.category} · **Strategy:** ${r.scrapable ? 'automated scrape' : 'link only'}`);
    lines.push(`- **Query:** \`${r.query}\` · **Status:** ${r.status === 'pass' ? '✅ pass' : '❌ fail'} (${r.detail}, ${r.durationMs}ms)`);
    if (r.searchUrl) lines.push(`- **Search URL:** <${r.searchUrl}>`);
    lines.push('');
    if (r.items.length > 0) {
      lines.push(`Top results extracted by the scraper:`);
      lines.push('');
      for (const it of r.items.slice(0, 5)) {
        const head = it.url ? `[${it.title}](${it.url})` : it.title;
        lines.push(`- **${head}**${it.subtitle ? ` — ${it.subtitle}` : ''}`);
        if (it.snippet) lines.push(`  - ${it.snippet.slice(0, 200)}`);
      }
      if (r.items.length > 5) lines.push(`- _…and ${r.items.length - 5} more._`);
      lines.push('');
    } else if (!r.scrapable) {
      lines.push(`_Link-only source — open the search URL above to view live results._`);
      lines.push('');
    } else {
      lines.push(`_No items extracted on this run — see the screenshot below for what the live search returned._`);
      lines.push('');
    }
    if (r.screenshotPath) {
      const rel = relative(OUT_DIR, r.screenshotPath);
      lines.push(`![${r.name}](${rel})`);
      lines.push('');
    }
  }

  await writeFile(REPORT_PATH, lines.join('\n'));
}

async function main(): Promise<void> {
  console.log(`\nE2E smoke — ${ALL_SOURCES.length} sources · screenshots → ${SHOT_DIR}\n`);
  await mkdir(SHOT_DIR, { recursive: true });
  const t0 = Date.now();
  const results: Result[] = [];
  for (const s of ALL_SOURCES) {
    process.stdout.write(`  … ${pad(s.id, 28)} ${D('(' + (s.scrape ? 'scrape' : 'link') + ')')}`);
    const r = await runOne(s);
    results.push(r);
    const icon = r.status === 'pass' ? G('✔') : R('✖');
    process.stdout.write(`\r  ${icon} ${pad(s.id, 28)} ${pad(`${r.durationMs}ms`, 8)} ${D(r.detail.slice(0, 80))}\n`);
  }
  const totalDurationMs = Date.now() - t0;

  await writeReport(results, totalDurationMs);

  const pass = results.filter((r) => r.status === 'pass').length;
  const fail = results.length - pass;
  console.log('');
  console.log(`Summary: ${G(pass + ' pass')} · ${fail ? R(fail + ' fail') : '0 fail'} / ${ALL_SOURCES.length} total (${(totalDurationMs / 1000).toFixed(1)}s)`);
  console.log(`Report:  ${REPORT_PATH}`);

  await closeBrowser();
  process.exit(fail ? 1 : 0);
}

void main();
